### Fetch songs request
GET http://localhost:3000/songs

### Find song request
GET http://localhost:3000/songs/2

### Create new song request
POST http://localhost:3000/songs
content-type: application/json

{
  "title": "Can You Hear The Music",
  "artists": ["Ludwig Göransson"],
  "releasedDate": "2023-07-21",
  "duration": "05:38"
}


### Update song request
PUT http://localhost:3000/songs/4
content-type: application/json

{
    "title": "Can You Hear The Music"
}


### Delete song request
DELETE http://localhost:3000/songs/2